/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package in.drongo.drongodb.util.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MemTableAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 59330340208732783L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MemTableAvro\",\"namespace\":\"in.drongo.drongodb.util.avro\",\"fields\":[{\"name\":\"balancedBST\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"record\",\"name\":\"FileEntryAvro\",\"fields\":[{\"name\":\"id\",\"type\":\"bytes\"},{\"name\":\"keyLen\",\"type\":\"bytes\"},{\"name\":\"key\",\"type\":\"bytes\"},{\"name\":\"valueLen\",\"type\":\"bytes\"},{\"name\":\"value\",\"type\":\"bytes\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MemTableAvro> ENCODER =
      new BinaryMessageEncoder<MemTableAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MemTableAvro> DECODER =
      new BinaryMessageDecoder<MemTableAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<MemTableAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<MemTableAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MemTableAvro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this MemTableAvro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a MemTableAvro from a ByteBuffer. */
  public static MemTableAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.Map<java.lang.CharSequence,in.drongo.drongodb.util.avro.FileEntryAvro> balancedBST;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MemTableAvro() {}

  /**
   * All-args constructor.
   * @param balancedBST The new value for balancedBST
   */
  public MemTableAvro(java.util.Map<java.lang.CharSequence,in.drongo.drongodb.util.avro.FileEntryAvro> balancedBST) {
    this.balancedBST = balancedBST;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return balancedBST;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: balancedBST = (java.util.Map<java.lang.CharSequence,in.drongo.drongodb.util.avro.FileEntryAvro>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'balancedBST' field.
   * @return The value of the 'balancedBST' field.
   */
  public java.util.Map<java.lang.CharSequence,in.drongo.drongodb.util.avro.FileEntryAvro> getBalancedBST() {
    return balancedBST;
  }

  /**
   * Sets the value of the 'balancedBST' field.
   * @param value the value to set.
   */
  public void setBalancedBST(java.util.Map<java.lang.CharSequence,in.drongo.drongodb.util.avro.FileEntryAvro> value) {
    this.balancedBST = value;
  }

  /**
   * Creates a new MemTableAvro RecordBuilder.
   * @return A new MemTableAvro RecordBuilder
   */
  public static in.drongo.drongodb.util.avro.MemTableAvro.Builder newBuilder() {
    return new in.drongo.drongodb.util.avro.MemTableAvro.Builder();
  }

  /**
   * Creates a new MemTableAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MemTableAvro RecordBuilder
   */
  public static in.drongo.drongodb.util.avro.MemTableAvro.Builder newBuilder(in.drongo.drongodb.util.avro.MemTableAvro.Builder other) {
    return new in.drongo.drongodb.util.avro.MemTableAvro.Builder(other);
  }

  /**
   * Creates a new MemTableAvro RecordBuilder by copying an existing MemTableAvro instance.
   * @param other The existing instance to copy.
   * @return A new MemTableAvro RecordBuilder
   */
  public static in.drongo.drongodb.util.avro.MemTableAvro.Builder newBuilder(in.drongo.drongodb.util.avro.MemTableAvro other) {
    return new in.drongo.drongodb.util.avro.MemTableAvro.Builder(other);
  }

  /**
   * RecordBuilder for MemTableAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MemTableAvro>
    implements org.apache.avro.data.RecordBuilder<MemTableAvro> {

    private java.util.Map<java.lang.CharSequence,in.drongo.drongodb.util.avro.FileEntryAvro> balancedBST;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(in.drongo.drongodb.util.avro.MemTableAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.balancedBST)) {
        this.balancedBST = data().deepCopy(fields()[0].schema(), other.balancedBST);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MemTableAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(in.drongo.drongodb.util.avro.MemTableAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.balancedBST)) {
        this.balancedBST = data().deepCopy(fields()[0].schema(), other.balancedBST);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'balancedBST' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,in.drongo.drongodb.util.avro.FileEntryAvro> getBalancedBST() {
      return balancedBST;
    }

    /**
      * Sets the value of the 'balancedBST' field.
      * @param value The value of 'balancedBST'.
      * @return This builder.
      */
    public in.drongo.drongodb.util.avro.MemTableAvro.Builder setBalancedBST(java.util.Map<java.lang.CharSequence,in.drongo.drongodb.util.avro.FileEntryAvro> value) {
      validate(fields()[0], value);
      this.balancedBST = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'balancedBST' field has been set.
      * @return True if the 'balancedBST' field has been set, false otherwise.
      */
    public boolean hasBalancedBST() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'balancedBST' field.
      * @return This builder.
      */
    public in.drongo.drongodb.util.avro.MemTableAvro.Builder clearBalancedBST() {
      balancedBST = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MemTableAvro build() {
      try {
        MemTableAvro record = new MemTableAvro();
        record.balancedBST = fieldSetFlags()[0] ? this.balancedBST : (java.util.Map<java.lang.CharSequence,in.drongo.drongodb.util.avro.FileEntryAvro>) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MemTableAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<MemTableAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MemTableAvro>
    READER$ = (org.apache.avro.io.DatumReader<MemTableAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
